# Generated by Django 4.0.1 on 2022-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', default='', max_length=20)),
                ('password', models.CharField(db_column='password', default='', max_length=200)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
