# Generated by Django 4.0.1 on 2022-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_notice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='order',
            field=models.PositiveIntegerField(db_column='order', default=1, max_length=50),
        ),
    ]
