# Generated by Django 4.0.1 on 2022-02-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_notice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='order',
            field=models.PositiveIntegerField(db_column='order', default=1),
        ),
    ]
