# Generated by Django 4.0.1 on 2022-02-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_notice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_column='order', default=1)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('content', models.CharField(db_column='content', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('author', models.CharField(db_column='author', max_length=20)),
                ('views', models.PositiveIntegerField(db_column='views', default=0)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
