# Generated by Django 4.0.1 on 2022-02-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_column='order', default=1)),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('sub_title', models.CharField(db_column='sub_title', max_length=50)),
                ('content', models.CharField(db_column='content', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('link', models.CharField(db_column='link', max_length=500)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
