# Generated by Django 4.0.1 on 2022-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_column='start')),
                ('end', models.DateField(db_column='end')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('content', models.CharField(db_column='content', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('image', models.ImageField(upload_to='media/images/popup')),
            ],
            options={
                'db_table': 'popup',
            },
        ),
    ]
