# Generated by Django 4.0.1 on 2022-02-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/popup'),
        ),
    ]
