# Generated by Django 4.0.1 on 2022-02-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productdetailimage_image_and_more'),
        ('support', '0008_alter_popup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(db_column='image', null=True, upload_to='media/images/popup'),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='category', max_length=50)),
                ('file', models.FileField(db_column='file', upload_to='media/download')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'download',
            },
        ),
    ]
