# Generated by Django 4.0.1 on 2022-02-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_popup_image_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id']},
        ),
    ]
