# Generated by Django 4.0.1 on 2022-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_download_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='type',
            field=models.CharField(db_column='type', max_length=50, null=True),
        ),
    ]
