# Generated by Django 4.0.1 on 2022-02-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_download_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='file',
        ),
        migrations.AddField(
            model_name='download',
            name='brochure',
            field=models.FileField(db_column='brochure', null=True, upload_to='media/download'),
        ),
        migrations.AddField(
            model_name='download',
            name='manual',
            field=models.FileField(db_column='manual', null=True, upload_to='media/download'),
        ),
        migrations.AddField(
            model_name='download',
            name='sheet',
            field=models.FileField(db_column='sheet', null=True, upload_to='media/download'),
        ),
    ]
