# Generated by Django 4.0.1 on 2022-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_alter_download_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
    ]
