# Generated by Django 4.0.1 on 2022-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(db_column='email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(db_column='file', null=True, upload_to='media/contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(db_column='password', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(db_column='type', max_length=50, null=True),
        ),
    ]
