# Generated by Django 4.0.1 on 2022-02-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_contact_email_contact_file_contact_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
