# Generated by Django 4.0.1 on 2022-02-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_delete_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='date', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='date', null=True),
        ),
    ]
