# Generated by Django 4.0.1 on 2022-03-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_contact_date_notice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
