# Generated by Django 4.0.3 on 2022-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_contact_date_notice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='image', null=True, upload_to='media/images/notice')),
            ],
            options={
                'db_table': 'notice_image',
            },
        ),
    ]
