# Generated by Django 4.0.1 on 2022-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_alter_notice_options_alter_video_options'),
        ('support', '0021_noticeimage'),
    ]

    operations = [
    ]
