# Generated by Django 4.0.1 on 2022-02-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='order', default=1, max_length=50),
        ),
    ]
