# Generated by Django 4.0.1 on 2022-02-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailimage',
            name='image',
            field=models.ImageField(upload_to='images/products/detail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/product'),
        ),
    ]
