# Generated by Django 4.0.1 on 2022-02-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetailimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailimage',
            name='image',
            field=models.ImageField(upload_to='media/images/product_detail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/images/product'),
        ),
    ]
