# Generated by Django 4.0.1 on 2022-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productdetailimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.CharField(db_column='main_category', max_length=50, null=True),
        ),
    ]
