# Generated by Django 4.0.1 on 2022-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.FileField(db_column='brochure', null=True, upload_to='media/download'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual',
            field=models.FileField(db_column='manual', null=True, upload_to='media/download'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet',
            field=models.FileField(db_column='sheet', null=True, upload_to='media/download'),
        ),
    ]
