# Generated by Django 4.0.1 on 2022-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_brochure_product_manual_product_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(db_column='type', max_length=50, null=True),
        ),
    ]
