# Generated by Django 4.0.1 on 2022-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(db_column='sub_category', default=None, max_length=50, null=True),
        ),
    ]
