# Generated by Django 4.0.1 on 2022-03-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prevent_detail',
            field=models.BooleanField(default=False),
        ),
    ]
