# Generated by Django 4.0.1 on 2022-03-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_prevent_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prevent_detail',
        ),
        migrations.AddField(
            model_name='product',
            name='show_detail',
            field=models.BooleanField(default=True),
        ),
    ]
